image: maven3:rel.1.1.0

variables:
#Module need to test
  MODULE: 'workspace'
#Environment need to test
  ENV: 'PRO_US'

stages:
  - build
#  - test
#- Core Product - FE

build:
  tags:
    - build
    - docker
  stage: build
  script:
    - mvn clean deploy -Dmaven.test.skip=true